apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: test1
  annotations:
    pod1/test1: sample
spec:
  containers:
    - name: nginx
      image: nginx


      #annoatations defines the behaviour
      #labbeling is noting but labelling your part
      #pod can read annoatations depends on that annoat it will work
      #inside spec it has list of containsers